# Toggle items.
items:
  # Whether helmets should break passively when worn. Happens very quickly.
  break-helmets: true

  # If set to true, `clear-god-apples` is ignored.
  clear-golden-apples: false
  clear-god-apples: true

  # You may disable potions by adding them to the blacklist.
  # Valid entries can be found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionType.html#enum-constant-summary
  potions:
    blacklist-enabled: true
    blacklist:
      - STRENGTH
      - LONG_STRENGTH
      - STRONG_STRENGTH



# In the real double life series, there's just one Enchantment Table.
# Players are also unable to craft bookshelves.
enchantments:
  table-craftable: false
  table-breakable: false

  bookshelves-craftable: false

  # Whether a max enchantment level of 2 is enforced by the plugin.
  nerf: false



# Toggle custom recipes. All of these were present in the real double life series.
custom-recipes:
  spore-blossom: true
  name-tag: true
  saddle: true
  paper-tnt: true



players:
  # The maximum (and default) amount of lives.
  max-lives: 3

  # Whether soulmates are revealed when randomizing pairs.
  reveal-soulmates: false

  # Whether a harmless lightning bolt should be cast at a player's last location when they run out of lives
  lightning-on-death: true

  # Whether offline players should be killed immediately upon rejoining if their soulmate dies
  # (Will give the player a notice in chat explaining why they've been killed)
  kill-on-rejoin: false